spring:
  datasource:
    write:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:jpa-self-study-write
      username: root
      password:
    read:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:jpa-self-study-read
      username: root
      password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
  output:
    ansi:
      enabled: always
