spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jpa-self-study;MODE=MYSQL;
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true
    open-in-view: false


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


